name: Trigger auto deployment for gat11-e-dev-contapps-po

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gat11-e-dev-contapps-po-AutoDeployTrigger-42f87ffd-ac78-49c1-9346-7d9e1dc4088f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GAT11EDEVCONTAPPSPO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GAT11EDEVCONTAPPSPO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GAT11EDEVCONTAPPSPO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: gat11eacr.azurecr.io
          registryUsername: ${{ secrets.GAT11EDEVCONTAPPSPO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GAT11EDEVCONTAPPSPO_REGISTRY_PASSWORD }}
          containerAppName: gat11-e-dev-contapps-po
          resourceGroup: gat11-e-dev-contapps-rg
          imageToBuild: gat11eacr.azurecr.io/gat11-e-dev-contapps-po:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


